### ISSUE TITLE
Not issuse i have a question

### ISSUE THREAD

**Issue by Soum-ik** [Nargis21/clean-hub-frontend#1]
In this project you are using Next JS, we know Next JS is a full-stack application so why you are using an external back end?  is there any extra advantage to this...

"I am curious to know about this." @Nargis21 apu

**Comment by nisharga** [comment]
> In this project you are using Next JS, we know Next JS is a full-stack application so why you are using an external back end? is there any extra advantage to this...
> 
> "I am curious to know about this." @Nargis21 apu

Because she is familiar with this
